version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /mnt/data --console-address ":9001"  # Command to run in container
    ports:
      - "9000:9000"  # MinIO server
      - "9001:9001"  # Console UI
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - type: bind
        source: ./data
        target: /mnt/data
      - type: bind
        source: ./config.env
        target: /etc/config.env
    restart: unless-stopped
  
  postgres:
    image: postgres
    container_name: sh-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin       
      POSTGRES_DB: test_database  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 20s
      retries: 3       
    restart: unless-stopped

  zookeeper:
    image: zookeeper
    container_name: zookeeper_service
    ports:
      - "2181:2181"  
      
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka_service
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 10.0.0.38:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.0.0.38:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

